{
   cuboids: {
      body_0: {
         dims: (12, 18, 10),
         uv: (30, 16)
      },
      body_1: {
         dims: (4, 6, 1),
         uv: (56, 4)
      },
      head_0: {
         dims: (8, 8, 6),
         uv: (8, 8)
      },
      head_1: {
         dims: (1, 3, 1),
         uv: (23, 1)
      },
      head_2: {
         dims: (1, 3, 1),
         uv: (23, 1)
      },
      leg1: {
         dims: (4, 12, 4),
         uv: (4, 20)
      },
      leg2: {
         dims: (4, 12, 4),
         uv: (4, 20)
      },
      leg3: {
         dims: (4, 12, 4),
         uv: (4, 20)
      },
      leg4: {
         dims: (4, 12, 4),
         uv: (4, 20)
      }
   },
   objects: {
      body: {
         cuboids: [
            {
               id: "body_0",
               pos: (-6, 11, -5)
            },
            {
               id: "body_1",
               pos: (-2, 11, -6)
            }
         ],
         pivot: (0, -19, -2)
      },
      head: {
         cuboids: [
            {
               id: "head_0",
               pos: (-4, 16, -14)
            },
            {
               id: "head_1",
               pos: (-5, 22, -12)
            },
            {
               id: "head_2",
               pos: (4, 22, -12)
            }
         ],
         pivot: (0, -20, 8)
      },
      leg1: {
         cuboids: [
            {
               id: "leg1",
               pos: (2, 0, 5)
            }
         ],
         pivot: (-4, -12, -7)
      },
      leg2: {
         cuboids: [
            {
               id: "leg2",
               pos: (-6, 0, 5)
            }
         ],
         pivot: (4, -12, -7)
      },
      leg3: {
         cuboids: [
            {
               id: "leg3",
               pos: (2, 0, -7)
            }
         ],
         pivot: (-4, -12, 6)
      },
      leg4: {
         cuboids: [
            {
               id: "leg4",
               pos: (-6, 0, -7)
            }
         ],
         pivot: (4, -12, 6)
      }
   }
}